version: '3'

services:
  php:
    build: docker/php
    container_name: php
    networks:
      - app_network
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./src:/var/www
    working_dir: /var/www/learning

networks:
  app_network:

volumes:
  mysql_volume:
